# Kela: Sairauspäivärahojen saajat ja maksetut etuudet diagnooseittain

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/Kela_diagnoosit_2024_2025.csv")
df.shape

(1186470, 15)

In [3]:
df.head(30)

,aikatyyppi,kuukausi_nro,vuosikuukausi,vuosi,kunta_nro,kunta_nimi,ikaryhma,sukupuoli,etuus,sairauspaaryhma,diagnoosi,saaja_lkm,maksettu_eur,korvattu_paiva_lkm,alkanut_kausi_lkm
0,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,Yhteensä,Yhteensä,293,387782.95,5931,203
1,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,Tieto puuttuu,Yhteensä,13,175.73,208,0
2,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,Tieto puuttuu,Tieto puuttuu,13,175.73,208,0
3,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",Yhteensä,40,41061.76,634,28
4,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",T81 Muualla luokittamattomat toimenpiteiden ko...,1,707.00,10,0
5,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S92 Jalkaterän luiden murtumat,2,1836.23,33,1
6,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S89 Muut tai määrittämättömät polven ja säären...,1,1373.28,16,1
7,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S82 Polven ja/tai säären murtuma,7,11740.96,155,6
8,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S80 Polven ja/tai säären pinnallinen vamma,2,371.50,4,2
9,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S72 Reisiluun murtuma,2,3871.76,54,1
10,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S63 Ranteen ja käden nivelten ja siteiden sijo...,1,195.60,3,0
11,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S62 Ranteen tai käden murtuma,3,3152.37,70,2
12,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S60 Ranteen ja/tai käden pinnallinen vamma,1,563.20,8,1
13,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S52 Kyynärvarren murtuma,7,6900.58,93,5
14,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S46 Hartianseudun ja olkavarren lihas- ja/tai ...,4,5507.54,91,3
15,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S43 Hartianseudun (hartiakaaren) nivelten ja s...,1,162.19,8,0
16,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S42 Hartianseudun tai olkavarren murtuma,5,5018.27,74,3
17,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S33 Lannerangan ja/tai lantion nivelten tai si...,1,174.24,2,1
18,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...","S22 Kylkiluun (kylkiluiden), rintalastan ja/ta...",2,1193.58,13,2
19,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"S00-T98 Vammat, myrkytykset ja eräät muut ulko...",S06 Kallonsisäinen vamma,0,-1706.54,0,0
20,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"R00-R99 Muualla luokittamattomat oireet, saira...",Yhteensä,6,4428.11,70,6
21,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"R00-R99 Muualla luokittamattomat oireet, saira...",R60 Muualla luokittamaton turvotus,1,1472.33,17,2
22,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"R00-R99 Muualla luokittamattomat oireet, saira...",R53 Huonovointisuus ja väsymys,2,510.64,12,2
23,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"R00-R99 Muualla luokittamattomat oireet, saira...",R41 Muut kognitiivisiin toimintoihin ja tajunn...,1,1873.90,35,0
24,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"R00-R99 Muualla luokittamattomat oireet, saira...",R10 Vatsa- ja lantiokipu,1,408.40,4,1
25,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"R00-R99 Muualla luokittamattomat oireet, saira...",R06 Hengityksen poikkeavuudet,1,162.84,2,1
26,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,N00-N99 Virtsa- ja sukupuolielinten sairaudet,Yhteensä,6,5875.48,91,6
27,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,N00-N99 Virtsa- ja sukupuolielinten sairaudet,N81 Naisen sukupuolielinten laskeuma,5,4131.66,53,5
28,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,N00-N99 Virtsa- ja sukupuolielinten sairaudet,N18 Pitkäaikainen munuaisten vajaatoiminta,1,1743.82,38,1
29,Vuosikertymä,1,202501,2025,0,Koko maa,65-67,Nainen,Yhteensä,"Muut pääryhmät (P00-P96,Q00-Q99,V01-Y98,Z00-ZB...",Z73 Elämäntilanteen hallintaan liittyvät ongelmat,1,1505.30,10,1

In [4]:
print(df["aikatyyppi"].unique())

['Vuosikertymä' 'Kuukausi']

In [5]:
print(df["kunta_nro"].unique())

[0]

In [6]:
print(df["kunta_nimi"].unique())

['Koko maa']

In [7]:
print(df["ikaryhma"].unique())

['65-67' '60-64' '25-29' '50-54' '45-49' '40-44' '35-39' '55-59' '30-34'
 '20-24' '16-19']

In [8]:
print(df["sukupuoli"].unique())

['Nainen' 'Mies']

In [9]:
print(df["diagnoosi"].unique())

['Yhteensä' 'Tieto puuttuu'
 'T81 Muualla luokittamattomat toimenpiteiden komplikaatiot' ...
 'L45 Muualla luokitettuun sairauteen liittyvä näppyläinen tai suomuileva ihottuma'
 'R85 Ruuansulatuselinten ja vatsaontelon näytteiden poikkeavat löydökset'
 'E40 Vaikea proteiinialiravitsemus']

In [10]:
print(df["etuus"].unique())

['Yhteensä' 'YEL-päiväraha' 'Sairauspäiväraha' 'Osasairauspäiväraha'
 'Tartuntatautipäiväraha' 'Luovutuspäiväraha']

In [11]:
df.value_counts("ikaryhma")

ikaryhma
55-59    152535
60-64    147745
50-54    141487
45-49    136495
40-44    131813
35-39    120608
30-34    111356
25-29     93571
20-24     71460
65-67     49146
16-19     30254
Name: count, dtype: int64

In [12]:
df.value_counts("sairauspaaryhma")

sairauspaaryhma
S00-T98 Vammat, myrkytykset ja eräät muut ulkoisten syiden seuraukset                                         159439
M00-M99 Tuki- ja liikuntaelinten sekä sidekudoksen sairaudet                                                  137216
C00-D48 Kasvaimet                                                                                             117853
F00-F99 Mielenterveyden ja käyttäytymisen häiriöt                                                              85222
K00-K93 Ruuansulatuselinten sairaudet                                                                          79435
G00-G99 Hermoston sairaudet                                                                                    78792
I00-I99 Verenkiertoelinten sairaudet                                                                           73533
J00-J99 Hengityselinten sairaudet                                                                              68599
R00-R99 Muualla luokittamattomat oireet, sairaudenmerkit sekä poikkeavat kliiniset ja laboratoriolöydökset     62693
Muut pääryhmät (P00-P96,Q00-Q99,V01-Y98,Z00-ZBB,U00-U99)                                                       59540
N00-N99 Virtsa- ja sukupuolielinten sairaudet                                                                  45325
A00-B99 Tartunta- ja loistauteja                                                                               43162
H00-H59 Silmän ja sen apuelinten sairaudet                                                                     40974
L00-L99 Ihon ja ihonalaiskudoksen sairaudet                                                                    38183
E00-E90 Umpierityssairaudet, ravitsemussairaudet ja aineenvaihduntasairaudet                                   31238
H60-H95 Korvan ja kartiolisäkkeen sairaudet                                                                    20584
D50-D89 Veren ja verta muodostavien elinten sairaudet sekä eräät immuunimekanismin häiriöt                     15976
O00-O99 Raskaus, synnytys ja lapsivuoteus                                                                      15419
Tieto puuttuu                                                                                                   8102
Yhteensä                                                                                                        5185
Name: count, dtype: int64

In [13]:
df.value_counts("diagnoosi")

diagnoosi
Yhteensä                                                                                     74217
Tieto puuttuu                                                                                 4051
F41 Muut ahdistuneisuushäiriöt                                                                3950
F32 Masennustila                                                                              3921
M54 Selkäsärky                                                                                3911
                                                                                             ...
K87 Muualla luokitettuihin sairauksiin liittyvät sappirakko-, sappitie- ja haimasairaudet        4
R85 Ruuansulatuselinten ja vatsaontelon näytteiden poikkeavat löydökset                          4
E40 Vaikea proteiinialiravitsemus                                                                4
Q69 Monisormisuus ja/tai monivarpaisuus                                                          4
R54 Seniliteetti (vanhusmaisuus)                                                                 4
Name: count, Length: 1437, dtype: int64

In [14]:
df.value_counts("aikatyyppi")

aikatyyppi
Vuosikertymä    743719
Kuukausi        442751
Name: count, dtype: int64

In [15]:
df_mieli = df[df["sairauspaaryhma"]=="F00-F99 Mielenterveyden ja käyttäytymisen häiriöt"]

In [16]:
df_mieli.value_counts("ikaryhma")

ikaryhma
30-34    9296
35-39    9133
25-29    9048
20-24    8880
40-44    8807
55-59    8283
45-49    8123
50-54    7850
60-64    7539
16-19    5873
65-67    2390
Name: count, dtype: int64

In [17]:
df_mieli.value_counts("diagnoosi")

diagnoosi
Yhteensä                                                                                                4059
F41 Muut ahdistuneisuushäiriöt                                                                          3950
F32 Masennustila                                                                                        3921
F43 Reaktiot vaikeaan stressiin ja sopeutumishäiriöt                                                    3868
F33 Toistuva masennus                                                                                   3752
                                                                                                        ...
F72 Vaikea älyllinen kehitysvammaisuus                                                                    26
F54 Muualla luokitettuun häiriöön tai sairauteen liittyvä psyykkinen tekijä tai käytöstekijä              20
F55 Riippuvuutta aiheuttamattomien aineiden väärinkäyttö                                                  18
F68 Muut aikuisiän persoonallisuus- ja käytöshäiriöt                                                      18
F59 Fysiologisiin häiriöihin ja ruumiillisiin tekijöihin liittyvät määrittämättömät käytösoireyhtymä      10
Name: count, Length: 76, dtype: int64

In [18]:
df_tules = df[df["sairauspaaryhma"]=="M00-M99 Tuki- ja liikuntaelinten sekä sidekudoksen sairaudet"]

In [19]:
df_tules.value_counts("ikaryhma")

ikaryhma
55-59    17458
60-64    16919
50-54    16418
45-49    15517
40-44    14779
35-39    13538
30-34    12446
25-29    10751
20-24     8479
65-67     7312
16-19     3599
Name: count, dtype: int64

In [20]:
df_tules.value_counts("diagnoosi")

diagnoosi
Yhteensä                                                                           4068
M54 Selkäsärky                                                                     3911
M51 Muut selän nikamavälilevyjen sairaudet                                         3700
M79 Muualla luokittamattomat muut pehmytkudossairaudet                             3694
M75 Hartianseudun pehmytkudossairaudet                                             3544
                                                                                   ...
M63 Muualla luokitettuihin sairauksiin liittyvät lihasten sairaudet                  26
M88 Pagetin luutauti                                                                 24
M36 Muualla luokitettuihin sairauksiin liittyvät systeemiset sidekudossairaudet      22
M73 Muualla luokitettuihin sairauksiin liittyvät pehmytkudossairaudet                12
M68 Muualla luokitettuihin sairauksiin liittyvät nivelkalvo- ja jännesairaudet        8
Name: count, Length: 79, dtype: int64

In [21]:
df = df.drop(columns=["vuosikuukausi", "kunta_nro", "kunta_nimi", "sairauspaaryhma"])

In [22]:
df.shape

(1186470, 11)

In [23]:
df = df[df["diagnoosi"] != "Yhteensä"]
df = df[df["diagnoosi"] != "Tieto puuttuu"]
df = df[df["saaja_lkm"] > 0]
df = df[df["maksettu_eur"] > 0]

In [24]:
df.shape

(1095344, 11)

In [25]:
df = df[df["korvattu_paiva_lkm"] > 0]

In [26]:
df.shape

(1093755, 11)

In [27]:
df.value_counts("diagnoosi")

diagnoosi
F41 Muut ahdistuneisuushäiriöt                          3948
M54 Selkäsärky                                          3907
F32 Masennustila                                        3906
F43 Reaktiot vaikeaan stressiin ja sopeutumishäiriöt    3859
F33 Toistuva masennus                                   3737
                                                        ...
T68 Hypotermia                                             4
E40 Vaikea proteiinialiravitsemus                          4
Q69 Monisormisuus ja/tai monivarpaisuus                    4
A35 Muu jäykkäkouristus                                    4
Z08 Pahanlaatuisen kasvaimen hoidon jälkitarkastus         4
Name: count, Length: 1430, dtype: int64

In [28]:
df.head(20)

,aikatyyppi,kuukausi_nro,vuosi,ikaryhma,sukupuoli,etuus,diagnoosi,saaja_lkm,maksettu_eur,korvattu_paiva_lkm,alkanut_kausi_lkm
4,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,T81 Muualla luokittamattomat toimenpiteiden ko...,1,707.00,10,0
5,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S92 Jalkaterän luiden murtumat,2,1836.23,33,1
6,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S89 Muut tai määrittämättömät polven ja säären...,1,1373.28,16,1
7,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S82 Polven ja/tai säären murtuma,7,11740.96,155,6
8,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S80 Polven ja/tai säären pinnallinen vamma,2,371.50,4,2
9,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S72 Reisiluun murtuma,2,3871.76,54,1
10,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S63 Ranteen ja käden nivelten ja siteiden sijo...,1,195.60,3,0
11,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S62 Ranteen tai käden murtuma,3,3152.37,70,2
12,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S60 Ranteen ja/tai käden pinnallinen vamma,1,563.20,8,1
13,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S52 Kyynärvarren murtuma,7,6900.58,93,5
14,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S46 Hartianseudun ja olkavarren lihas- ja/tai ...,4,5507.54,91,3
15,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S43 Hartianseudun (hartiakaaren) nivelten ja s...,1,162.19,8,0
16,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S42 Hartianseudun tai olkavarren murtuma,5,5018.27,74,3
17,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,S33 Lannerangan ja/tai lantion nivelten tai si...,1,174.24,2,1
18,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,"S22 Kylkiluun (kylkiluiden), rintalastan ja/ta...",2,1193.58,13,2
21,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,R60 Muualla luokittamaton turvotus,1,1472.33,17,2
22,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,R53 Huonovointisuus ja väsymys,2,510.64,12,2
23,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,R41 Muut kognitiivisiin toimintoihin ja tajunn...,1,1873.90,35,0
24,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,R10 Vatsa- ja lantiokipu,1,408.40,4,1
25,Vuosikertymä,1,2025,65-67,Nainen,Yhteensä,R06 Hengityksen poikkeavuudet,1,162.84,2,1

In [29]:
df.tail(20)

,aikatyyppi,kuukausi_nro,vuosi,ikaryhma,sukupuoli,etuus,diagnoosi,saaja_lkm,maksettu_eur,korvattu_paiva_lkm,alkanut_kausi_lkm
1186450,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M85 Muut luun tiheyden ja rakenteen häiriöt,1,1064.25,25,0
1186451,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M84 Luun rakentumisen häiriöt,12,14635.59,245,5
1186452,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M79 Muualla luokittamattomat muut pehmytkudoss...,73,79158.32,1357,42
1186453,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M77 Muut siteiden ja lihasjänteiden kiinnittym...,57,63276.50,1054,33
1186454,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M76 Alaraajan (jalkaterää lukuun ottamatta) si...,17,19309.07,333,11
1186455,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M75 Hartianseudun pehmytkudossairaudet,99,98678.21,1846,53
1186456,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M72 Fibroblastisairaudet,12,10015.67,193,8
1186457,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M71 Muut limapussisairaudet,3,4349.53,65,2
1186458,Kuukausi,5,2025,45-49,Nainen,Yhteensä,"M70 Käytön, ylirasituksen ja/tai paineen aiheu...",8,8704.52,152,5
1186459,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M67 Muut nivelkalvo- ja jännesairaudet,4,3151.04,53,4
1186460,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M65 Nivelkalvon tai jännetupen tulehdus,23,17512.51,334,14
1186461,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M62 Muut lihasten sairaudet,5,3670.39,94,4
1186462,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M54 Selkäsärky,172,215601.43,3951,91
1186463,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M53 Muualla luokittamattomat muut selkäsairaudet,18,20378.08,349,10
1186464,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M51 Muut selän nikamavälilevyjen sairaudet,87,136379.36,2445,33
1186465,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M50 Kaularangan välilevysairaudet,32,40816.19,736,15
1186466,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M48 Muut nikamasairaudet,14,16191.51,270,7
1186467,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M47 Spondyloosi,32,34737.67,648,10
1186468,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M46 Muut tulehdukselliset nikamasairaudet,2,2023.47,9,1
1186469,Kuukausi,5,2025,45-49,Nainen,Yhteensä,M43 Muut epämuotoisuutta aiheuttavat selkäsair...,20,27967.31,534,8

In [30]:
df_w = df[df["sukupuoli"]=="Nainen"]
df_w.value_counts("diagnoosi")

diagnoosi
F41 Muut ahdistuneisuushäiriöt                                                                          2025
F32 Masennustila                                                                                        1982
F43 Reaktiot vaikeaan stressiin ja sopeutumishäiriöt                                                    1977
M54 Selkäsärky                                                                                          1967
F51 Ei-elimelliset unihäiriöt                                                                           1927
                                                                                                        ...
Q69 Monisormisuus ja/tai monivarpaisuus                                                                    4
G01 Aivokalvotulehdus muualla luokitetun bakteeritaudin yhteydessä                                         4
F04 Elimellinen amnestinen oireyhtymä, joka ei ole alkoholin eikä muiden psyykeen vaikuttavien ainei       4
K87 Muualla luokitettuihin sairauksiin liittyvät sappirakko-, sappitie- ja haimasairaudet                  4
M91 Lasten lonkkanivelen ja lantion osteokondroosi                                                         4
Name: count, Length: 1314, dtype: int64

In [31]:
df_m = df[df["sukupuoli"]=="Mies"]
df_m.value_counts("diagnoosi")

diagnoosi
M54 Selkäsärky                                                             1940
F32 Masennustila                                                           1924
F41 Muut ahdistuneisuushäiriöt                                             1923
F43 Reaktiot vaikeaan stressiin ja sopeutumishäiriöt                       1882
M51 Muut selän nikamavälilevyjen sairaudet                                 1849
                                                                           ...
L63 Pälvikaljuus                                                              4
Z43 Tekoaukon huolto                                                          4
D63 Muualla luokitettuihin pitkäaikaisiin sairauksiin liittyvä anemia         4
H67 Muualla luokitettuihin sairauksiin liittyvät välikorvan tulehdukset       4
T68 Hypotermia                                                                4
Name: count, Length: 1218, dtype: int64

In [32]:
df = df.sample(frac=1).reset_index(drop=True)

In [33]:
print((df["saaja_lkm"] == 0).sum())
print((df["maksettu_eur"] == 0).sum())

0
0

In [34]:
print(df["saaja_lkm"].isna().sum())
print(df["korvattu_paiva_lkm"].isna().sum())
print(df["maksettu_eur"].isna().sum())

0
0
0

In [35]:
print(df["saaja_lkm"].min())
print(df["maksettu_eur"].min())
print(df["korvattu_paiva_lkm"].min())
print(df["saaja_lkm"].max())
print(df["maksettu_eur"].max())
print(df["korvattu_paiva_lkm"].max())

1
0.09
1
4306
10395968.25
180748

In [36]:
df["ka_paiva_lkm"] = df["korvattu_paiva_lkm"].div(df["saaja_lkm"])
df["ka_maksettu/paiva"] = df["maksettu_eur"].div(df["korvattu_paiva_lkm"])
df = df.round({"ka_paiva_lkm": 2, "ka_maksettu/paiva":2})

In [37]:
df = df.drop(columns=["saaja_lkm", "maksettu_eur", "korvattu_paiva_lkm"])

In [38]:
df.head()

,aikatyyppi,kuukausi_nro,vuosi,ikaryhma,sukupuoli,etuus,diagnoosi,alkanut_kausi_lkm,ka_paiva_lkm,ka_maksettu/paiva
0,Vuosikertymä,7,2025,30-34,Nainen,Yhteensä,D15 Muiden ja määrittämättömien rintaontelon e...,1,45.00,68.97
1,Vuosikertymä,11,2024,30-34,Mies,Yhteensä,R33 Virtsaumpi,1,15.00,74.53
2,Vuosikertymä,2,2025,45-49,Nainen,Sairauspäiväraha,E03 Muu kilpirauhasen vajaatoiminta,1,15.00,71.43
3,Vuosikertymä,11,2025,30-34,Mies,Sairauspäiväraha,F64 Sukupuoli-identiteetin häiriöt,15,13.37,58.64
4,Vuosikertymä,3,2025,45-49,Mies,Sairauspäiväraha,S53 Kyynärnivelen seudun nivelten tai siteiden...,4,22.25,68.71

In [39]:
df.to_csv("data/diagnoosit.csv", index=False)

In [40]:
print((df["ka_paiva_lkm"] == 0).sum())
print((df["ka_maksettu/paiva"] == 0).sum())
print(df["ka_paiva_lkm"].isna().sum())
print(df["ka_maksettu/paiva"].isna().sum())
print(df["ka_paiva_lkm"].min())
print(df["ka_maksettu/paiva"].min())
print(df["ka_paiva_lkm"].max())
print(df["ka_maksettu/paiva"].max())

0
0
0
0
0.33
0.01
308.0
3002.88