In [2]:
import numpy as np
import pandas as pd

In [3]:
kumpula19 = pd.read_csv("data/Kumpula_2019.csv")
kumpula20 = pd.read_csv("data/Kumpula_2020.csv")
kumpula21 = pd.read_csv("data/Kumpula_2021.csv")
kumpula22 = pd.read_csv("data/Kumpula_2022.csv")
kumpula23 = pd.read_csv("data/Kumpula_2023.csv")
kumpula24 = pd.read_csv("data/Kumpula_2024.csv")
kumpula25 = pd.read_csv("data/Kumpula_2025.csv")
kumpula19 = kumpula19[kumpula19["Vallitseva sää"].isin(['Heikkoa lumisadetta', 'Heikkoja vesikuuroja', 'Utua', 'Heikkoa vesisadetta', 'Tihkusadetta tai lumijyväsiä edellisen tunnin aikana, mutta ei enää havaintohetkellä', 'Heikkoa tai kohtalaista sadetta', 'Heikkoja lumikuuroja'])]
kumpula20 = kumpula20[kumpula20["Vallitseva sää"].isin(['Heikkoa lumisadetta', 'Heikkoja vesikuuroja', 'Utua', 'Heikkoa vesisadetta', 'Tihkusadetta tai lumijyväsiä edellisen tunnin aikana, mutta ei enää havaintohetkellä', 'Heikkoa tai kohtalaista sadetta', 'Heikkoja lumikuuroja'])]
kumpula21 = kumpula21[kumpula21["Vallitseva sää"].isin(['Heikkoa lumisadetta', 'Heikkoja vesikuuroja', 'Utua', 'Heikkoa vesisadetta', 'Tihkusadetta tai lumijyväsiä edellisen tunnin aikana, mutta ei enää havaintohetkellä', 'Heikkoa tai kohtalaista sadetta', 'Heikkoja lumikuuroja'])]
kumpula22 = kumpula22[kumpula22["Vallitseva sää"].isin(['Heikkoa lumisadetta', 'Heikkoja vesikuuroja', 'Utua', 'Heikkoa vesisadetta', 'Tihkusadetta tai lumijyväsiä edellisen tunnin aikana, mutta ei enää havaintohetkellä', 'Heikkoa tai kohtalaista sadetta', 'Heikkoja lumikuuroja'])]
kumpula23 = kumpula23[kumpula23["Vallitseva sää"].isin(['Heikkoa lumisadetta', 'Heikkoja vesikuuroja', 'Utua', 'Heikkoa vesisadetta', 'Tihkusadetta tai lumijyväsiä edellisen tunnin aikana, mutta ei enää havaintohetkellä', 'Heikkoa tai kohtalaista sadetta', 'Heikkoja lumikuuroja'])]
kumpula24 = kumpula24[kumpula24["Vallitseva sää"].isin(['Heikkoa lumisadetta', 'Heikkoja vesikuuroja', 'Utua', 'Heikkoa vesisadetta', 'Tihkusadetta tai lumijyväsiä edellisen tunnin aikana, mutta ei enää havaintohetkellä', 'Heikkoa tai kohtalaista sadetta', 'Heikkoja lumikuuroja'])]
kumpula25 = kumpula25[kumpula25["Vallitseva sää"].isin(['Heikkoa lumisadetta', 'Heikkoja vesikuuroja', 'Utua', 'Heikkoa vesisadetta', 'Tihkusadetta tai lumijyväsiä edellisen tunnin aikana, mutta ei enää havaintohetkellä', 'Heikkoa tai kohtalaista sadetta', 'Heikkoja lumikuuroja'])]

In [4]:
kumpula_19_25 = pd.concat([kumpula19, kumpula20, kumpula21, kumpula22, kumpula23, kumpula24, kumpula25])
kumpula_19_25.head()

,Havaintoasema,Vuosi,Kuukausi,Päivä,Aika [Paikallinen aika],Näkyvyys keskiarvo [m],Ilman lämpötila keskiarvo [°C],Pilvisyys [1/8],Suhteellinen kosteus keskiarvo [%],Vallitseva sää,Tuulen suunta keskiarvo [°],Keskituulen nopeus keskiarvo [m/s]
0,Helsinki Kumpula,2019,1,1,00:00,1559,0.4,Pilvistä (8/8),95.8,Heikkoa lumisadetta,204.3,9
1,Helsinki Kumpula,2019,1,1,01:00,1663,0.4,Pilvistä (8/8),97.3,Heikkoa lumisadetta,197.5,9.4
3,Helsinki Kumpula,2019,1,1,03:00,3017,1.2,Pilvistä (8/8),96.8,Heikkoa vesisadetta,213.1,9.3
9,Helsinki Kumpula,2019,1,1,09:00,5848,2.9,Pilvistä (8/8),98.5,Heikkoa vesisadetta,193.2,7.9
17,Helsinki Kumpula,2019,1,1,17:00,20085,2.5,Melko pilvistä (7/8),98,Tihkusadetta tai lumijyväsiä edellisen tunnin ...,226.7,4.4

In [5]:
kumpula_19_25.shape

(10838, 12)

In [6]:
kumpula_19_25["Pilvisyys [1/8]"] = kumpula_19_25["Pilvisyys [1/8]"].str[-4]
kumpula_19_25.columns = kumpula_19_25.columns.str.replace("[", "(")
kumpula_19_25.columns = kumpula_19_25.columns.str.replace("]", ")")

In [7]:
#kumpula_19_25 = pd.read_csv("data/kumpula_19-25.csv")

In [8]:
kumpula_19_25 = kumpula_19_25.sample(frac=1).reset_index(drop=True)
kumpula_19_25.head()

,Havaintoasema,Vuosi,Kuukausi,Päivä,Aika (Paikallinen aika),Näkyvyys keskiarvo (m),Ilman lämpötila keskiarvo (°C),Pilvisyys (1/8),Suhteellinen kosteus keskiarvo (%),Vallitseva sää,Tuulen suunta keskiarvo (°),Keskituulen nopeus keskiarvo (m/s)
0,Helsinki Kumpula,2020,12,29,00:00,19170,1.3,8,90.4,Heikkoa vesisadetta,126.9,10
1,Helsinki Kumpula,2022,2,13,09:00,10301,0.9,7,93.8,Heikkoa lumisadetta,216.9,8.5
2,Helsinki Kumpula,2021,2,6,04:00,2346,-16.3,7,85.2,Heikkoa lumisadetta,326.1,3.7
3,Helsinki Kumpula,2025,4,18,10:00,7363,7.7,8,98,Utua,112.1,2.7
4,Helsinki Kumpula,2023,9,9,00:00,8917,15.8,0,97.3,Utua,124.5,1.6

In [9]:
kumpula_19_25["Tunti (Paikallinen aika)"] = kumpula_19_25["Aika (Paikallinen aika)"].str[0:2]
kumpula_19_25 = kumpula_19_25.drop(columns=["Havaintoasema", "Aika (Paikallinen aika)"])

In [10]:
kumpula_19_25.head()

,Vuosi,Kuukausi,Päivä,Näkyvyys keskiarvo (m),Ilman lämpötila keskiarvo (°C),Pilvisyys (1/8),Suhteellinen kosteus keskiarvo (%),Vallitseva sää,Tuulen suunta keskiarvo (°),Keskituulen nopeus keskiarvo (m/s),Tunti (Paikallinen aika)
0,2020,12,29,19170,1.3,8,90.4,Heikkoa vesisadetta,126.9,10,00
1,2022,2,13,10301,0.9,7,93.8,Heikkoa lumisadetta,216.9,8.5,09
2,2021,2,6,2346,-16.3,7,85.2,Heikkoa lumisadetta,326.1,3.7,04
3,2025,4,18,7363,7.7,8,98,Utua,112.1,2.7,10
4,2023,9,9,8917,15.8,0,97.3,Utua,124.5,1.6,00

In [11]:
kumpula_19_25.shape

(10838, 11)

In [10]:
kumpula_19_25.to_csv("data/FI_kumpula_19-25.csv", index=False)